# log_min_duration_statement = 1000 # Logue seulement les requêtes qui durent plus de 1 seconde
# listen_addresses = '127.0.0.1'
autovacuum_max_workers = 3
autovacuum_vacuum_cost_delay = 10ms
autovacuum_vacuum_cost_limit = 2000
checkpoint_completion_target = 0.9 # checkpoint target duration, 0.0 - 1.0
datestyle = 'iso, dmy'
default_statistics_target = 200
effective_cache_size = 5GB
effective_io_concurrency = 200 # 1-1000; 0 disables prefetching
listen_addresses = ''
log_checkpoints = off
log_directory = '/var/log/postgresql/' # directory where log files are written,
log_duration = off
log_error_verbosity = default # terse, default, or verbose messages
log_file_mode = 0666 # creation mode for log files,
log_filename = 'postgresql-%Y-%m-%d_%H_%M_%S.log' # log file name pattern,
log_hostname = on
log_line_prefix = '\n%m [%r] \n'
log_min_duration_statement = -1 # -1 is disabled, 0 logs all statements // \d{2,}\.\d{3}\sms
log_min_error_statement = error # values in order of decreasing detail:
log_min_messages = warning # error (warning) values in order of decreasing detail:
log_rotation_age = 28d # Automatic rotation of logfiles will
log_statement = 'none' # none, ddl, mod, all
log_timezone = 'Europe/Paris'
logging_collector = on # Enable capturing of stderr, jsonlog,
maintenance_work_mem = 512MB
max_connections = 100 # (change requires restart)
max_parallel_maintenance_workers = 4
max_parallel_workers = 8 # maximum number of max_worker_processes that
max_parallel_workers_per_gather = 4
max_wal_size = 5GB
max_worker_processes = 8 # (change requires restart)
min_wal_size = 2GB
password_encryption = scram-sha-256 # scram-sha-256 or md5
random_page_cost = 1.1 # same scale as above
scram_iterations = 8192
shared_buffers = 2500MB # min 128kB
timezone = 'Europe/Paris'
unix_socket_directories = '/var/run/postgresql'
wal_buffers = -1 # 16MB # min 32kB, -1 sets based on shared_buffers
work_mem = 64MB # min 64kB
