user_pref ('app.normandy.api_url', '');
user_pref ('app.normandy.enabled', false);
user_pref ('app.shield.optoutstudies.enabled', false);
user_pref ('app.update.BITS.enabled', false);
user_pref ('app.update.auto', false);
user_pref ('app.update.auto.migrated', false);
user_pref ('app.update.checkInstallTime', false);
user_pref ('app.update.disabledForTesting', true);
user_pref ('app.update.doorhanger', false);
user_pref ('app.update.enabled', false);
user_pref ('app.update.mode', 0);
user_pref ('app.update.service.enabled', false);
user_pref ('app.update.staging.enabled', false);
user_pref ('apz.overscroll.enabled', true);
user_pref ('beacon.enabled', false);
user_pref ('breakpad.reportURL', '');
user_pref ('browser.aboutConfig.showWarning', false);
user_pref ('browser.aboutHomeSnippets.updateUrL', '');
user_pref ('browser.cache.disk.enable', false);
user_pref ('browser.cache.disk_cache_ssl', true);
user_pref ('browser.cache.memory.enable', true);
user_pref ('browser.cache.offline.enable', false);
user_pref ('browser.chrome.guess_favicon', false);
user_pref ('browser.crashReports.unsubmittedCheck.autoSubmit2', false);
user_pref ('browser.crashReports.unsubmittedCheck.enabled', false);
user_pref ('browser.discovery.enabled', false);
user_pref ('browser.dom.window.dump.enabled', true);
user_pref ('browser.download.animateNotifications', false);
user_pref ('browser.download.folderList', 2);
user_pref ('browser.download.useDownloadDir', true);
user_pref ('browser.fixup.alternate.suffix', '.fr');
user_pref ('browser.newtabpage.activity-stream.asrouter.providers.cfr',
           'null');
user_pref (
    'browser.newtabpage.activity-stream.asrouter.providers.message-groups',
    'null');
user_pref (
    'browser.newtabpage.activity-stream.asrouter.providers.messaging-experiments',
    'null');
user_pref ('browser.newtabpage.activity-stream.asrouter.providers.snippets',
           'null');
user_pref (
    'browser.newtabpage.activity-stream.asrouter.providers.whats-new-panel',
    'null');
user_pref ('browser.newtabpage.activity-stream.default.sites', '');
user_pref ('browser.newtabpage.activity-stream.discoverystream.config', '[]');
user_pref ('browser.newtabpage.activity-stream.feeds.snippets', false);
user_pref ('browser.newtabpage.activity-stream.feeds.system.topstories',
           false);
user_pref ('browser.newtabpage.activity-stream.feeds.telemetry', false);
user_pref ('browser.newtabpage.activity-stream.fxaccounts.endpoint', '');
user_pref ('browser.newtabpage.activity-stream.showSponsored', false);
user_pref ('browser.newtabpage.activity-stream.showSponsoredTopSites', false);
user_pref ('browser.newtabpage.activity-stream.telemetry', false);
user_pref (
    'browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint',
    '');
user_pref ('browser.newtabpage.activity-stream.tippyTop.service.endpoint', '');
user_pref ('browser.newtabpage.enabled', true);
user_pref ('browser.pagethumbnails.capturing_disabled', true);
user_pref ('browser.ping-centre.telemetry', false);
user_pref ('browser.places.speculativeConnect.enabled', false);
user_pref ('browser.safebrowsing.downloads.enabled', false);
user_pref ('browser.safebrowsing.downloads.remote.block_dangerous', false);
user_pref ('browser.safebrowsing.downloads.remote.block_dangerous_host',
           false);
user_pref ('browser.safebrowsing.downloads.remote.block_potentially_unwanted',
           false);
user_pref ('browser.safebrowsing.downloads.remote.block_uncommon', false);
user_pref ('browser.safebrowsing.downloads.remote.enabled', false);
user_pref ('browser.safebrowsing.downloads.remote.url', '');
user_pref ('browser.safebrowsing.enabled', false);
user_pref ('browser.safebrowsing.malware.enabled', false);
user_pref ('browser.safebrowsing.phishing.enabled', false);
user_pref ('browser.safebrowsing.provider.google.advisoryName',
           'Gogol Relatively Safe Browsing');
user_pref ('browser.safebrowsing.provider.google.advisoryURL', '');
user_pref ('browser.safebrowsing.provider.google.gethashURL', '');
user_pref ('browser.safebrowsing.provider.google.lists', '');
user_pref ('browser.safebrowsing.provider.google.reportMalwareMistakeURL', '');
user_pref ('browser.safebrowsing.provider.google.reportPhishMistakeURL', '');
user_pref ('browser.safebrowsing.provider.google.reportURL', '');
user_pref ('browser.safebrowsing.provider.google.updateURL', '');
user_pref ('browser.safebrowsing.provider.google4.advisoryURL', '');
user_pref ('browser.safebrowsing.provider.google4.dataSharingURL', '');
user_pref ('browser.safebrowsing.provider.google4.gethashURL', '');
user_pref ('browser.safebrowsing.provider.google4.lists', '');
user_pref ('browser.safebrowsing.provider.google4.reportMalwareMistakeURL',
           '');
user_pref ('browser.safebrowsing.provider.google4.reportPhishMistakeURL', '');
user_pref ('browser.safebrowsing.provider.google4.reportURL', '');
user_pref ('browser.safebrowsing.provider.google4.updateURL', '');
user_pref ('browser.search.geoip.url', '');
user_pref ('browser.search.region', 'US');
user_pref ('browser.search.removeEngineInfobar.enabled', false);
user_pref ('browser.search.suggest.enabled', false);
user_pref ('browser.selfsupport.url', '');
user_pref ('browser.send_pings', false);
user_pref ('browser.send_pings.require_same_host', true);
user_pref ('browser.sessionstore.max_tabs_undo', 40);
user_pref ('browser.sessionstore.resume_from_crash', false);
user_pref ('browser.startup.homepage', 'about:home');
user_pref ('browser.startup.homepage_override.buildID', '');
user_pref ('browser.startup.homepage_override.mstone', 'ignore');
user_pref ('browser.startup.page', 0);
user_pref ('browser.tabs.animate', false);
user_pref ('browser.tabs.crashReporting.sendReport', false);
user_pref ('browser.urlbar.merino.endpointURL', '');
user_pref ('browser.urlbar.placeholderName', 'Google');
user_pref ('browser.urlbar.speculativeConnect.enabled', false);
user_pref ('browser.urlbar.suggest.searches', false);
user_pref ('browser.urlbar.usepreloadedtopurls.enabled', false);
user_pref ('browser.webapps.checkForUpdates', 0);
user_pref ('captivedetect.canonicalURL', '');
user_pref ('config.trim_on_minimize', true);
user_pref ('datareporting.healthreport.documentServerURI', '');
user_pref ('datareporting.healthreport.uploadEnabled', false);
user_pref ('datareporting.policy.dataSubmissionEnabled', false);
user_pref ('datareporting.policy.dataSubmissionPolicyBypassNotification',
           false);
user_pref ('devtools.console.stdout.chrome', true);
user_pref ('devtools.debugger.remote-enabled', false);
user_pref ('dom.allow_scripts_to_close_windows', false);
user_pref ('dom.battery.enabled', false);
user_pref ('dom.disable_image_src_set', false);
user_pref ('dom.disable_open_during_load', '');
user_pref ('dom.disable_window_flip', true);
user_pref ('dom.disable_window_move_resize', true);
user_pref ('dom.event.clipboardevents.enabled', false);
user_pref ('dom.event.contextmenu.enabled', false);
user_pref ('dom.forms.autocomplete.formautofill', true);
user_pref ('dom.forms.datetime.others', false);
user_pref ('dom.gamepad.enabled', false);
user_pref ('dom.gamepad.non_standard_events.enabled', false);
user_pref ('dom.push.connection.enabled', false);
user_pref ('dom.push.serverURL', '');
user_pref ('dom.security.https_only_mode', true);
user_pref ('dom.security.unexpected_system_load_telemetry_enabled', false);
user_pref ('dom.w3c_touch_events.enabled', 0);
user_pref ('dom.workers.requestAnimationFrame', false);
user_pref ('experiments.activeExperiment', false);
user_pref ('experiments.enabled', false);
user_pref ('experiments.supported', false);
user_pref ('extensions.blocklist.enabled', false);
user_pref ('extensions.checkCompatibility', false);
user_pref ('extensions.formautofill.addresses.available', 'on');
user_pref ('extensions.formautofill.creditCards.available', 'on');
user_pref ('extensions.getAddons.showPane', false);
user_pref ('extensions.htmlaboutaddons.recommendations.enabled', false);
user_pref ('extensions.pocket.api', '');
user_pref ('extensions.pocket.enabled', false);
user_pref ('extensions.pocket.oAuthConsumerKey', '');
user_pref ('extensions.pocket.site', '');
user_pref ('general.smoothScroll', true);
user_pref ('general.smoothScroll.currentVelocityWeighting', 1.0);
user_pref ('general.smoothScroll.lines.durationMaxMS', 100);
user_pref ('general.smoothScroll.lines.durationMinMS', 100);
user_pref ('general.smoothScroll.msdPhysics.enabled', true);
user_pref ('general.smoothScroll.msdPhysics.slowdownMinDeltaRatio', 100);
user_pref ('general.smoothScroll.msdPhysics.slowdownMinDeltaRatio', 2.0);
user_pref ('general.smoothScroll.other.durationMaxMS', 100);
user_pref ('general.smoothScroll.other.durationMinMS', 100);
user_pref ('general.smoothScroll.pages.durationMaxMS', 100);
user_pref ('general.smoothScroll.pages.durationMinMS', 100);
user_pref ('general.smoothScroll.pixels.durationMaxMS', 100);
user_pref ('general.smoothScroll.pixels.durationMinMS', 100);
user_pref ('general.smoothScroll.scrollbars.durationMaxMS', 100);
user_pref ('general.smoothScroll.scrollbars.durationMinMS', 100);
user_pref ('general.smoothScroll.stopDecelerationWeighting', 1.0);
user_pref ('geo.enabled', false);
user_pref ('geo.provider.network.logging.enabled', false);
user_pref ('geo.provider.network.scan', false);
user_pref ('geo.provider.network.url', '');
user_pref ('geo.provider.testing', false);
user_pref ('geo.provider.use_corelocation', false);
user_pref ('geo.provider.use_geoclue', false);
user_pref ('geo.provider.use_gpsd', false);
user_pref ('geo.wifi.uri', '');
user_pref ('gfx.offscreencanvas.enabled', false);
user_pref ('gfx.webrender.all', true);
user_pref ('html5.offmainthread', true) // Caution
user_pref ('image.animation_mode', 'none');
user_pref ('javascript.options.asyncstack', false);
user_pref ('layers.acceleration.force-enabled', true);
user_pref ('layers.async-video.enabled', true);
user_pref ('layers.offmainthreadcomposition.async-animations', true);
user_pref ('layers.offmainthreadcomposition.enabled', true);
user_pref ('layout.css.initial-letter.enabled', false);
user_pref ('layout.css.prefers-color-scheme.content-override', 0);
user_pref ('layout.css.scroll-behavior.enabled', false);
user_pref ('layout.frame_rate.precise', true);
user_pref ('loop.enabled', false);
user_pref ('media.allowed-to-play.enabled', false);
user_pref ('media.autoplay.block-webaudio', true);
user_pref ('media.autoplay.default', 1);
user_pref ('media.av1.enabled', false);
user_pref ('media.block-autoplay-until-in-foreground', true);
user_pref ('media.block-play-until-visible', true);
user_pref ('media.eme.enabled', false);
user_pref ('media.ffmpeg.vaapi.enabled', true);
user_pref ('media.mediasource.mp4.enabled', false);
user_pref ('media.mediasource.webm.enabled', false);
user_pref ('media.peerconnection.enabled', false);
user_pref ('media.video_stats.enabled', false);
user_pref ('mousewheel.default.delta_multiplier_y', 400); // 250-400;
user_pref ('network.IDN_show_punycode', true);
user_pref ('network.allow-experiments', false);
user_pref ('network.captive-portal-service.enabled', false);
user_pref ('network.connectivity-service.enabled', false);
user_pref ('network.cookie.alwaysAcceptSessionCookies', false);
user_pref ('network.cookie.cookieBehavior', 1);
user_pref ('network.dns.disableIPv6', true);
user_pref ('network.dns.disablePrefetch', true);
user_pref ('network.dns.disablePrefetchFromHTTPS', true);
user_pref ('network.dnsCacheEntries', 500);
user_pref ('network.dnsCacheExpiration', 1200);
user_pref ('network.dnsCacheExpirationGracePeriod', 1200);
user_pref ('network.http.http2.websockets', false);
user_pref ('network.http.referer.XOriginPolicy', 1);
user_pref ('network.http.referer.XOriginTrimmingPolicy', 2);
user_pref ('network.http.referer.defaultPolicy', 1);
user_pref ('network.http.referer.defaultPolicy.pbmode', 1);
user_pref ('network.http.referer.defaultPolicy.trackers', 0);
user_pref ('network.http.referer.defaultPolicy.trackers.pbmode', 0);
user_pref ('network.http.referer.spoofSource', true);
user_pref ('network.http.referer.trimmingPolicy', 2);
user_pref ('network.http.sendRefererHeader', 0);
user_pref ('network.http.sendSecureXSiteReferrer', false);
user_pref ('network.http.speculative-parallel-limit', 0);
user_pref ('network.manage-offline-status', false);
user_pref ('network.predictor.enable-prefetch', false);
user_pref ('network.predictor.enabled', false);
user_pref ('network.prefetch-next', false);
user_pref ('network.preload', false);
user_pref ('network.trr.mode', 5);
user_pref ('network.websocket.delay-failed-reconnects', false);
user_pref ('network.websocket.enabled', false);
user_pref ('network.websocket.max-connections', 0);
user_pref ('pdfjs.disabled', true);
user_pref ('pdfjs.enabledCache.state', true);
user_pref ('pdfjs.migrationVersion', 2);
user_pref ('permissions.default.camera', 2);
user_pref ('permissions.default.desktop-notification', 2);
user_pref ('permissions.default.geo', 2);
user_pref ('permissions.default.microphone', 2);
user_pref ('plugin.state.java', 0);
user_pref ('plugins.enumerable_names', '');
user_pref ('privacy.clearOnShutdown.cache', true);
user_pref ('privacy.clearOnShutdown.cookies', false);
user_pref ('privacy.clearOnShutdown.sessions', false)
user_pref ('privacy.clearOnShutdown.siteSettings', false);
user_pref ('privacy.donottrackheader.enabled', true);
user_pref ('privacy.fingerprintingProtection', true);
user_pref ('privacy.fingerprintingProtection.pbmode', true);
user_pref ('privacy.partition.always_partition_third_party_non_cookie_storage',
           true);
user_pref ('privacy.resistFingerprinting', true);
user_pref ('privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts',
           true);
user_pref ('privacy.resistFingerprinting.block_mozAddonManager', true);
user_pref ('privacy.resistFingerprinting.pbmode', true);
user_pref ('privacy.resistFingerprinting.randomization.daily_reset.enabled',
           true);
user_pref (
    'privacy.resistFingerprinting.randomization.daily_reset.private.enabled',
    true);
user_pref ('privacy.resistFingerprinting.randomization.enabled', true);
user_pref ('privacy.sanitize.sanitizeOnShutdown', false);
user_pref ('privacy.trackingprotection.enabled', true);
user_pref ('remote.experimental.enabled', false);
user_pref ('security.OCSP.enable', 1);
user_pref ('security.app_menu.recordEventTelemetry', false);
user_pref ('security.certerrors.recordEventTelemetry', false);
user_pref ('security.identitypopup.recordEventTelemetry', false);
user_pref ('security.protectionspopup.recordEventTelemetry', false);
user_pref ('security.remote_settings.intermediates.enabled', true);
user_pref ('security.ssl3.ecdhe_ecdsa_aes_128_sha', false);
user_pref ('security.ssl3.ecdhe_ecdsa_aes_256_sha', false);
user_pref ('security.ssl3.ecdhe_rsa_aes_128_sha', false);
user_pref ('security.ssl3.ecdhe_rsa_aes_256_sha', false);
user_pref ('security.ssl3.rsa_aes_128_gcm_sha256', false);
user_pref ('security.ssl3.rsa_aes_128_sha', false);
user_pref ('security.ssl3.rsa_aes_256_gcm_sha384', false);
user_pref ('security.ssl3.rsa_aes_256_sha', false);
user_pref ('security.tls.version.max', 4);
user_pref ('security.tls.version.min', 3);
user_pref (
    'security.turn_off_all_security_so_that_viruses_can_take_over_this_computer',
    false);
user_pref ('startup.homepage_welcome_url', '');
user_pref ('startup.homepage_welcome_url.additional',
           'about:setup | about:config');
user_pref ('toolkit.content-background-hang-monitor.disabled', true);
user_pref ('toolkit.cosmeticAnimations.enabled', false);
user_pref ('toolkit.coverage.endpoint.base', '');
user_pref ('toolkit.coverage.opt-out', true);
user_pref ('toolkit.telemetry.archive.enabled', false);
user_pref ('toolkit.telemetry.bhrPing.enabled', false);
user_pref ('toolkit.telemetry.cachedClientID', '');
user_pref ('toolkit.telemetry.coverage.opt-out', true);
user_pref ('toolkit.telemetry.dap_helper', '');
user_pref ('toolkit.telemetry.dap_helper_owner', '');
user_pref ('toolkit.telemetry.dap_leader', '');
user_pref ('toolkit.telemetry.enabled', false);
user_pref ('toolkit.telemetry.firstShutdownPing.enabled', false);
user_pref ('toolkit.telemetry.hybridContent.enabled', false);
user_pref ('toolkit.telemetry.newProfilePing.enabled', false);
user_pref ('toolkit.telemetry.pioneer-new-studies-available', false);
user_pref ('toolkit.telemetry.reportingpolicy.firstRun', false);
user_pref ('toolkit.telemetry.server', 'data:,')
user_pref ('toolkit.telemetry.server_owner', '');
user_pref ('toolkit.telemetry.shutdownPingSender.enabled', false);
user_pref ('toolkit.telemetry.unified', false);
user_pref ('toolkit.telemetry.updatePing.enabled', false);
user_pref ('ui.prefersReducedMotion', 1);
user_pref ('ui.systemUsesDarkTheme', 1);
user_pref ('webgl.disabled', true);
user_pref ('webgl.force-enabled', false);
