# you can choose themes from $HOME/.config/kitty/kitty-themes/
include ./kitty-themes/00-Default.conf

background #141414
background_opacity 1
bold_font auto
bold_italic_font auto
confirm_os_window_close 0
cursor #DB193B
cursor_trail 0
disable_ligatures never
dynamic_background_opacity no
enable_audio_bell no
enable_gpu_renderer yes
font_antialias rgb
font_family "FiraCode Nerd Font"
font_hinting full
font_size 16
foreground #EAEAEA
italic_font auto
linux_display_server auto
repaint_delay 5
resize_draw_strategy static
scrollback_lines 5000
selection_background none
selection_foreground none
selection_knows_about_bidi no
smooth_scrolling yes
wheel_scroll_min_lines 3
window_padding_width 6
