#!/usr/bin/zsh

alias apts='pacman -Ss'
alias grepd="grep -i removed /var/log/pacman.log | perl -pe 's/(?<=\d{2})T(?=\d{2})/ à /p'| perl -pe 's/:\d{2}\+(.*?)\d{4}//p' | grep -e 'removed'"
alias grepi="grep -i installed /var/log/pacman.log | perl -pe 's/(?<=\d{2})T(?=\d{2})/ à /p'| perl -pe 's/:\d{2}\+(.*?)\d{4}//p' | grep -e 'installed'"
alias grepo="grep -i upgraded /var/log/pacman.log | perl -pe 's/(?<=\d{2})T(?=\d{2})/ à /p'| perl -pe 's/:\d{2}\+(.*?)\d{4}//p' | grep -e 'upgraded'"
alias i='sudo pacman -Syu --overwrite '\''*'\'
alias ii='pacman -Qii'
alias inst='pacman -Syu'
alias maj='sudo pacman -Syu --overwrite '\''*'\'
alias pacfiles='pacman -F'
alias pacfileupg='sudo pacman -Fy'
alias pacin='sudo pacman -S'
alias pacins='sudo pacman -U'
alias pacinsd='sudo pacman -S --asdeps'
alias paclean='sudo pacman -Sc'
alias pacloc='pacman -Qi'
alias paclocs='pacman -Qs'
alias paclr='sudo pacman -Scc'
alias pacls='pacman -Ql'
alias paclsorphans='sudo pacman -Qdt'
alias pacmanallkeys='sudo pacman-key --refresh-keys'
alias pacmir='sudo pacman -Syy'
alias pacown='pacman -Qo'
alias pacre='sudo pacman -R'
alias pacrem='sudo pacman -Rns'
alias pacrep='pacman -Si'
alias pacreps='pacman -Ss'
alias pacrmorphans='sudo pacman -Rs $(pacman -Qtdq)'
alias pacupd="sudo pacman -Sy"
alias pacupd='sudo pacman -Sy'
alias pacupg='sudo pacman -Syu'
alias r='pacman -Rsc'
alias rc='pacman -Rsc'
alias si='pacman -Ss'
alias sif='s=$1 ; _sif(){ pacman -Qlq "$1" | grep -v "/$" | xargs -r du -h | sort -h }; _sif'
alias sii='pacman -Qq | fzf --preview '\''pacman -Qil {}'\'' --layout=reverse --bind '\''enter:execute(pacman -Qil {} | less)'\'
alias siii='pacman -Slq | fzf --preview '\''pacman -Si {}'\'' --layout=reverse'
alias ug='pacman -Syyu'
