-- SPDX-License-Identifier: CC0-1.0
-- vim:syntax=lua:set ts=4 sw=4:
-- Refer to manual: https://knot-resolver.readthedocs.org/en/stable/

-- /etc/fstab
-- tmpfs /var/cache/knot-resolver tmpfs rw,size=2500M,uid=knot-resolver,gid=knot-resolver,nosuid,nodev,noexec,mode=0700 0 0

logfile = '/var/log/knot-resolver.log'

-- Configuration de l'interface réseau (écoute locale uniquement)
net.listen('127.0.0.1', 53, { kind = 'dns' })

-- Charge les modules utiles
modules = {
    'hints > iterate',     -- Active le chargement de /etc/hosts ou de root hints personnalisés
    'policy',              -- Active le moteur de politiques DNS
    'detect_time_jump',    -- Gère les sauts temporels du système
}

-- Configure la taille du cache DNS
cache.size = 1200 * MB     -- Définit la taille du cache
cache.max_ttl(86400)       -- Définit la durée maximale de vie du cache (1 jour)
cache.min_ttl(300)         -- Définit la durée minimale de vie du cache (5 minutes)

-- Définit le niveau de journalisation
log_level('err')

dofile('/etc/knot-resolver/blocklist-custom.lua')

-- Redirige toutes les requêtes DNS via TLS vers des résolveurs filtrants
policy.add(
  policy.all(
    policy.TLS_FORWARD({
        {'80.67.169.12', hostname='ns0.fdn.fr'},
        {'80.67.169.40', hostname='ns1.fdn.fr'},  
        {'1.1.1.1', hostname='cloudflare-dns.com'},
        {'1.0.0.1', hostname='cloudflare-dns.com'},
        {'8.8.8.8', hostname='dns.google'},
        {'8.8.4.4', hostname='dns.google'},
        {'9.9.9.11', hostname='dns11.quad9.net'},
        {'149.112.112.11', hostname='dns11.quad9.net'}    
        })
    )
)
