[general]
live_config_reload = true

[window.padding]
x = 5
y = 0

[window]
dimensions = { columns = 120, lines = 35 }
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[cursor]
style = "Beam"
unfocused_hollow = true

[colors.cursor]
cursor = "0xDB193B"
text = "0xf1c1c1"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 16
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }


[scrolling]
history = 10000
multiplier = 3

[mouse]
bindings = [{ mouse= "Right", mods = "Control", action = "Paste" }]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[colors]
[colors.primary]
background = "0x141414"
foreground = "0xEAEAEA"

[debug]
log_level = "Warn"
persistent_logging = false
render_timer = false

[terminal]
osc52 = "OnlyCopy"

[keyboard]
bindings = [
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "N", mods = "Command", command = { program = "open", args = ["-nb", "io.alacritty"] } },
  { key = "Home", mode = "AppCursor", chars = "\u001BOH" },
  { key = "Home", mode = "~AppCursor", chars = "\u001B[H" },
  { key = "End", mode = "AppCursor", chars = "\u001BOF" },
  { key = "End", mode = "~AppCursor", chars = "\u001B[F" },
  { key = "Key0", mods = "Command", action = "ResetFontSize" },
  { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "PageUp", mods = "Shift", chars = "\u001B[5;2~" },
  { key = "PageUp", mods = "Control", chars = "\u001B[5;5~" },
  { key = "PageUp", chars = "\u001B[5~" },
  { key = "PageDown", mods = "Shift", chars = "\u001B[6;2~" },
  { key = "PageDown", mods = "Control", chars = "\u001B[6;5~" },
  { key = "PageDown", chars = "\u001B[6~" },
  { key = "Tab", mods = "Shift", chars = "\u001B[Z" },
  { key = "Back", chars = "\u007F" },
  { key = "Back", mods = "Alt", chars = "\u001B\u007F" },
  { key = "Insert", chars = "\u001B[2~" },
  { key = "Delete", chars = "\u001B[3~" },
  # Flèches gauche
  { key = "Left", mods = "Shift", chars = "\u001B[1;2D" },
  { key = "Left", mods = "Control", chars = "\u001B[1;5D" },
  { key = "Left", mods = "Alt", chars = "\u001B[1;3D" },
  { key = "Left", mode = "~AppCursor", chars = "\u001B[D" },
  { key = "Left", mode = "AppCursor", chars = "\u001BOD" },
  # Flèches droite
  { key = "Right", mods = "Shift", chars = "\u001B[1;2C" },
  { key = "Right", mods = "Control", chars = "\u001B[1;5C" },
  { key = "Right", mods = "Alt", chars = "\u001B[1;3C" },
  { key = "Right", mode = "~AppCursor", chars = "\u001B[C" },
  { key = "Right", mode = "AppCursor", chars = "\u001BOC" },
  # Flèches haut
  { key = "Up", mods = "Shift", chars = "\u001B[1;2A" },
  { key = "Up", mods = "Control", chars = "\u001B[1;5A" },
  { key = "Up", mods = "Alt", chars = "\u001B[1;3A" },
  { key = "Up", mode = "~AppCursor", chars = "\u001B[A" },
  { key = "Up", mode = "AppCursor", chars = "\u001BOA" },
  # Flèches bas
  { key = "Down", mods = "Shift", chars = "\u001B[1;2B" },
  { key = "Down", mods = "Control", chars = "\u001B[1;5B" },
  { key = "Down", mods = "Alt", chars = "\u001B[1;3B" },
  { key = "Down", mode = "~AppCursor", chars = "\u001B[B" },
  { key = "Down", mode = "AppCursor", chars = "\u001BOB" },
  # Touches F1–F12 et variantes
  { key = "F1", chars = "\u001BOP" },
  { key = "F2", chars = "\u001BOQ" },
  { key = "F3", chars = "\u001BOR" },
  { key = "F4", chars = "\u001BOS" },
  { key = "F5", chars = "\u001B[15~" },
  { key = "F6", chars = "\u001B[17~" },
  { key = "F7", chars = "\u001B[18~" },
  { key = "F8", chars = "\u001B[19~" },
  { key = "F9", chars = "\u001B[20~" },
  { key = "F10", chars = "\u001B[21~" },
  { key = "F11", chars = "\u001B[23~" },
  { key = "F12", chars = "\u001B[24~" },
  # Shift + Fx
  { key = "F1", mods = "Shift", chars = "\u001B[1;2P" },
  { key = "F2", mods = "Shift", chars = "\u001B[1;2Q" },
  { key = "F3", mods = "Shift", chars = "\u001B[1;2R" },
  { key = "F4", mods = "Shift", chars = "\u001B[1;2S" },
  { key = "F5", mods = "Shift", chars = "\u001B[15;2~" },
  { key = "F6", mods = "Shift", chars = "\u001B[17;2~" },
  { key = "F7", mods = "Shift", chars = "\u001B[18;2~" },
  { key = "F8", mods = "Shift", chars = "\u001B[19;2~" },
  { key = "F9", mods = "Shift", chars = "\u001B[20;2~" },
  { key = "F10", mods = "Shift", chars = "\u001B[21;2~" },
  { key = "F11", mods = "Shift", chars = "\u001B[23;2~" },
  { key = "F12", mods = "Shift", chars = "\u001B[24;2~" },
  # Control + Fx
  { key = "F1", mods = "Control", chars = "\u001B[1;5P" },
  { key = "F2", mods = "Control", chars = "\u001B[1;5Q" },
  { key = "F3", mods = "Control", chars = "\u001B[1;5R" },
  { key = "F4", mods = "Control", chars = "\u001B[1;5S" },
  { key = "F5", mods = "Control", chars = "\u001B[15;5~" },
  { key = "F6", mods = "Control", chars = "\u001B[17;5~" },
  { key = "F7", mods = "Control", chars = "\u001B[18;5~" },
  { key = "F8", mods = "Control", chars = "\u001B[19;5~" },
  { key = "F9", mods = "Control", chars = "\u001B[20;5~" },
  { key = "F10", mods = "Control", chars = "\u001B[21;5~" },
  { key = "F11", mods = "Control", chars = "\u001B[23;5~" },
  { key = "F12", mods = "Control", chars = "\u001B[24;5~" },
  # Alt + Fx
  { key = "F1", mods = "Alt", chars = "\u001B[1;6P" },
  { key = "F2", mods = "Alt", chars = "\u001B[1;6Q" },
  { key = "F3", mods = "Alt", chars = "\u001B[1;6R" },
  { key = "F4", mods = "Alt", chars = "\u001B[1;6S" },
  { key = "F5", mods = "Alt", chars = "\u001B[15;6~" },
  { key = "F6", mods = "Alt", chars = "\u001B[17;6~" },
  { key = "F7", mods = "Alt", chars = "\u001B[18;6~" },
  { key = "F8", mods = "Alt", chars = "\u001B[19;6~" },
  { key = "F9", mods = "Alt", chars = "\u001B[20;6~" },
  { key = "F10", mods = "Alt", chars = "\u001B[21;6~" },
  { key = "F11", mods = "Alt", chars = "\u001B[23;6~" },
  { key = "F12", mods = "Alt", chars = "\u001B[24;6~" },
  # Command + Fx
  { key = "F1", mods = "Command", chars = "\u001B[1;3P" },
  { key = "F2", mods = "Command", chars = "\u001B[1;3Q" },
  { key = "F3", mods = "Command", chars = "\u001B[1;3R" },
  { key = "F4", mods = "Command", chars = "\u001B[1;3S" },
  { key = "F5", mods = "Command", chars = "\u001B[15;3~" },
  { key = "F6", mods = "Command", chars = "\u001B[17;3~" },
  { key = "F7", mods = "Command", chars = "\u001B[18;3~" },
  { key = "F8", mods = "Command", chars = "\u001B[19;3~" },
  { key = "F9", mods = "Command", chars = "\u001B[20;3~" },
  { key = "F10", mods = "Command", chars = "\u001B[21;3~" },
  { key = "F11", mods = "Command", chars = "\u001B[23;3~" },
  { key = "F12", mods = "Command", chars = "\u001B[24;3~" },
  # tmux-like
  { key = "D", mods = "Command", chars = "\u0006v" },
  { key = "D", mods = "Command|Shift", chars = "\u0006s" },
  { key = "W", mods = "Command", chars = "\u0006x" },
  { key = "H", mods = "Command", chars = "\u0006h" },
  { key = "J", mods = "Command", chars = "\u0006j" },
  { key = "K", mods = "Command", chars = "\u0006k" },
  { key = "L", mods = "Command", chars = "\u0006l" },
  { key = "T", mods = "Command", chars = "\u0006c" },
  { key = "RBracket", mods = "Command|Shift", chars = "\u0006n" },
  { key = "LBracket", mods = "Command|Shift", chars = "\u0006p" },
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
  # Command + chiffres
  { key = "Key1", mods = "Command", chars = "\u00061" },
  { key = "Key2", mods = "Command", chars = "\u00062" },
  { key = "Key3", mods = "Command", chars = "\u00063" },
  { key = "Key4", mods = "Command", chars = "\u00064" },
  { key = "Key5", mods = "Command", chars = "\u00065" },
  { key = "Key6", mods = "Command", chars = "\u00066" },
  { key = "Key7", mods = "Command", chars = "\u00067" },
  { key = "Key8", mods = "Command", chars = "\u00068" },
  { key = "Key9", mods = "Command", chars = "\u00069" },
  # Command + flèches
  { key = "Left", mods = "Command", chars = "\u0006H" },
  { key = "Down", mods = "Command", chars = "\u0006J" },
  { key = "Up", mods = "Command", chars = "\u0006K" },
  { key = "Right", mods = "Command", chars = "\u0006L" }
]
