#!/usr/bin/zsh

###### JetBrains ######
alias android-studio="nohup /opt/AndroidStudio/bin/studio > /dev/null 2>&1 >/dev/null 2>&1 &"
alias aqua="nohup /opt/JetBrains/Aqua/bin/aqua > /dev/null 2>&1 >/dev/null 2>&1 &"
alias astudio="nohup /opt/JetBrains/AndroidStudio/bin/studio > /dev/null 2>&1 >/dev/null 2>&1 &"
alias clion="nohup /opt/JetBrains/Clion/bin/clion > /dev/null 2>&1 >/dev/null 2>&1 &"
alias rustrover="nohup /opt/JetBrains/RustRover/bin/rustrover > /dev/null 2>&1 >/dev/null 2>&1 &"
alias dbeaver="nohup dbeaver > /dev/null 2>&1 >/dev/null 2>&1 &"
alias dg="nohup /opt/JetBrains/DataGrip/bin/datagrip > /dev/null 2>&1 >/dev/null 2>&1 &"
alias gitkraken="nohup /opt/gitkraken/gitkraken > /dev/null 2>&1 >/dev/null 2>&1 &"
alias insomnia="nohup /opt/Insomnium/insomnium >/dev/null 2>&1 &"
alias insomnium="nohup /opt/Insomnium/insomnium >/dev/null 2>&1 &"
alias intelj="nohup /opt/JetBrains/IntelliJ/bin/idea > /dev/null 2>&1 >/dev/null 2>&1 &"
alias intj="nohup /opt/JetBrains/IntelliJ/bin/idea > /dev/null 2>&1 >/dev/null 2>&1 &"
alias masterpdf="nohup masterpdfeditor5 >/dev/null 2>&1 &"
alias ph="nohup /opt/JetBrains/PHPStorm/bin/phpstorm > /dev/null 2>&1 >/dev/null 2>&1 &"
alias postman="nohup /opt/Postman/app/postman >/dev/null 2>&1 &"
alias pyc="nohup /opt/JetBrains/PyCharm/bin/pycharm > /dev/null 2>&1 >/dev/null 2>&1 &"
alias pych="nohup /opt/JetBrains/PyCharm/bin/pycharm > /dev/null 2>&1 >/dev/null 2>&1 &"
alias pycharm="nohup /opt/JetBrains/PyCharm/bin/pycharm > /dev/null 2>&1 >/dev/null 2>&1 &"
alias rubyc="nohup /opt/JetBrains/RubyMine/bin/rubymine > /dev/null 2>&1 >/dev/null 2>&1 &"
alias rubych="nohup /opt/JetBrains/RubyMine/bin/rubymine > /dev/null 2>&1 >/dev/null 2>&1 &"
alias rubycha="nohup /opt/JetBrains/RubyMine/bin/rubymine > /dev/null 2>&1 >/dev/null 2>&1 &"
alias web="nohup /opt/JetBrains/WebStorm/bin/webstorm > /dev/null 2>&1 >/dev/null 2>&1 &"
alias goland="nohup /opt/JetBrains/GoLand/bin/goland > /dev/null 2>&1 >/dev/null 2>&1 &"
###### --------- ######
